[workspace]
members = [
  "tsuyu_cli",
  "tsuyu",
  "tsuyu_chars",
  "tsuyu_error",
  "tsuyu_source",
  "tsuyu_token",
  "tsuyu_ast",
  "tsuyu_lexer",
  "tsuyu_parser",
  "tsuyuir",
  "tsuyuir_codegen",
  "tsuyu_asserts",
  "tsuyu_utils",
]
