[package]
name = "tsuyu_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
paste = "1.0"

[dev-dependencies]
tsuyu_asserts = { path = "../tsuyu_asserts" }
