name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: zakuro9715/setup-z@main
    - name: Setup
      run: z setup
    - name: Build
      run: z build --verbose
    - name: Lint
      run: z lint --verbose
    - name: Run tests
      run: z test.cov --out xml --verbose
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
